### ISSUE TITLE
pytorch version

### ISSUE THREAD

**Issue by MOHAMEDELDAKDOUKY** [LSIbabnikz/FaceQAN#2]
Can you please share your PyTorch and python versions used in this work? 

 Thanks!

**Comment by zb4290** [comment]
Hi,
the versions used in this project are Python 3.8 and PyTorch 1.10.

**Comment by MOHAMEDELDAKDOUKY** [comment]
Thanks for your reply! 

I still get the following error trying to run the calculate_qs.py script, can you help with that? 

Thanks!

`####################################################################################################            
=> Running FaceQAN over 1 images, using the following configuration:            
         -> ε = 0.001            
         -> l = 5            
         -> k = 10            
         -> p = 5            
####################################################################################################
Traceback (most recent call last):
  File "calculate_qs.py", line 106, in <module>
    qs = __calculate_score_batch__(args.image_paths, args.epsilon, args.bim_iterations, args.batch_size, args.exponent)
  File "calculate_qs.py", line 67, in __calculate_score_batch__
    model : torch.nn.Module = load_cosface().eval().cuda()
  File "/media/avidbeam/workspace/dakdouky_ws/face_quality/repos/FaceQAN/src/util.py", line 31, in load_cosface
    return lc()
  File "/media/avidbeam/workspace/dakdouky_ws/face_quality/repos/FaceQAN/src/models/iresnet.py", line 207, in load_cosface
    model.load_state_dict(torch.load(os.path.join(os.path.dirname(__file__), "weights.pth")))
  File "/home/avidbeam/.virtualenvs/torch101/lib/python3.8/site-packages/torch/serialization.py", line 600, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/avidbeam/.virtualenvs/torch101/lib/python3.8/site-packages/torch/serialization.py", line 242, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: Expected hasRecord("version") to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)`

**Comment by GalileoC** [comment]
Same error, did you fix this?

**Comment by TheNha** [comment]
Hi. I got the same error, did you fix this?
